//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetParameter
    {
        public int ID { get; set; }
        public Nullable<bool> RECORDTYPE { get; set; }
        public string KDV { get; set; }
        public string ACCOUNTCODE { get; set; }
        public string NOTACCOUNTCODE { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string COMPANY { get; set; }
    }
}
