//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostDetail
    {
        public int ID { get; set; }
        public Nullable<int> COSTGROUPID { get; set; }
        public string NAME { get; set; }
        public string UNITTYPE { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    }
}
