//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostToolNose
    {
        public int ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string TOOLTIP { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> CAPACITY { get; set; }
        public Nullable<int> TOOLNOSE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> CURRENCY { get; set; }
        public Nullable<int> CREATEDUSER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
