//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErpConnection
    {
        public int ID { get; set; }
        public string VT_NAME { get; set; }
        public string VT_USERNAME { get; set; }
        public string VT_USERPASS { get; set; }
        public string ERP_USER { get; set; }
        public string ERP_PASS { get; set; }
    }
}
