//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOrder
    {
        public int ID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public string COSTUMERCODE { get; set; }
        public string COSTUMERNAME { get; set; }
        public string SALESPERSON { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string PAYMENTTYPE { get; set; }
        public Nullable<int> CURRENCY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> CHANGEDATE { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<System.DateTime> PAYMENTDATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> FINISHEDAMOUNT { get; set; }
    }
}
