//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanlamaLog
    {
        public int ID { get; set; }
        public string ISLEM { get; set; }
        public string ISLEM_NO { get; set; }
        public Nullable<int> ISLEM_USER { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ESKI { get; set; }
        public string YENI { get; set; }
        public string FARK { get; set; }
    }
}
