//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeRequest
    {
        public int ID { get; set; }
        public string OEMNO { get; set; }
        public string ACIKLAMA { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public byte[] DOSYA { get; set; }
        public string STOK_KODU { get; set; }
    }
}
