//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTarget
    {
        public int ID { get; set; }
        public string PLASIYER_KODU { get; set; }
        public string PLASIYER_ACIKLAMA { get; set; }
        public string CARI_KODU { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<int> PB { get; set; }
        public string ULKE_KODU { get; set; }
    }
}
