//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeplinFlow.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YMKFLOWEntities : DbContext
    {
        public YMKFLOWEntities()
            : base("name=YMKFLOWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetAccount> BudgetAccounts { get; set; }
        public virtual DbSet<BudgetGroup> BudgetGroups { get; set; }
        public virtual DbSet<BudgetParameter> BudgetParameters { get; set; }
        public virtual DbSet<BudgetSubgroup> BudgetSubgroups { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CostDetail> CostDetails { get; set; }
        public virtual DbSet<CostGroup> CostGroups { get; set; }
        public virtual DbSet<CostToolNose> CostToolNoses { get; set; }
        public virtual DbSet<ErpConnection> ErpConnections { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MoldDocument> MoldDocuments { get; set; }
        public virtual DbSet<MoldProductionTime> MoldProductionTimes { get; set; }
        public virtual DbSet<PaymentOrder> PaymentOrders { get; set; }
        public virtual DbSet<PlanlamaLog> PlanlamaLogs { get; set; }
        public virtual DbSet<ProductCostList> ProductCostLists { get; set; }
        public virtual DbSet<ProjeGroup> ProjeGroups { get; set; }
        public virtual DbSet<ProjeParameter> ProjeParameters { get; set; }
        public virtual DbSet<ProjeRequest> ProjeRequests { get; set; }
        public virtual DbSet<ProjeStatu> ProjeStatus { get; set; }
        public virtual DbSet<ReqNote> ReqNotes { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<SalesTarget> SalesTargets { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
